"""Hardened 8-class YOLO training entry point for TrackSense.

The trained model uses 8 CONTIGUOUS model-local classes; `counter` (canonical 7)
is excluded and `bread` is canonical 8 -> model-local 7. The authoritative
mapping lives in ml/class_schema.py and is printed on every run.

Preflight fails fast (before any GPU time is spent) on:
  - missing data yaml / missing dataset directories
  - empty train or valid split
  - a schema that is not exactly the 8 model-local classes
  - a `counter` class appearing anywhere in the yaml
  - bread not sitting at model-local id 7
  - any label carrying a class id outside 0..7
  - remaining exact cross-split (SHA-256) duplicate leakage

Model choice is NOT defaulted: `--model` is required for training. The project's
real prior run used `yolo26n.pt` (see model/checkpoints/best.pt train_args); the
older script wrongly defaulted to `yolov8n.pt`. No family is switched silently.
"""

from __future__ import annotations

import argparse
import hashlib
import platform
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from ml.class_schema import (
    CANONICAL_TO_MODEL_LOCAL,
    EXCLUDED_FROM_TRAINING,
    MODEL_LOCAL_NAMES,
    MODEL_LOCAL_TO_CANONICAL,
    NUM_TRAINING_CLASSES,
    TRAINING_MODE,
    training_names,
)

DEFAULT_DATASET_ROOT = REPO_ROOT / "data" / "training_8class_balanced"
RESOLVED_YAML = REPO_ROOT / "ml" / "data.train.resolved.yaml"
DEDUP_REPORT = REPO_ROOT / "reports" / "dedup_report.csv"
SPLITS = ("train", "valid", "test")
IMAGE_EXTENSIONS = {".bmp", ".jpeg", ".jpg", ".png", ".tif", ".tiff", ".webp"}
RECOMMENDED_MODEL = "yolo26n.pt"


def write_resolved_yaml(dataset_root: Path) -> Path:
    names = training_names()
    lines = [
        "# AUTO-GENERATED by ml/train_yolo.py -- do not edit, do not commit.",
        f"# schema={TRAINING_MODE} ({NUM_TRAINING_CLASSES} classes); names from ml/class_schema.py",
        "# counter (canonical 7) excluded; bread canonical 8 -> model-local 7.",
        f"path: {dataset_root.as_posix()}",
        "train: train/images",
        "val: valid/images",
        "test: test/images",
        "",
        "names:",
    ]
    for index in sorted(names):
        lines.append(f"  {index}: {names[index]}")
    RESOLVED_YAML.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return RESOLVED_YAML


def count_images(directory: Path) -> int:
    if not directory.is_dir():
        return 0
    return sum(1 for p in directory.iterdir() if p.suffix.lower() in IMAGE_EXTENSIONS)


def sha256_of(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def print_mapping() -> None:
    print("Class schema")
    print("-" * 12)
    print(f"mode: {TRAINING_MODE}  ({NUM_TRAINING_CLASSES} model-local classes)")
    print(f"excluded from model: {EXCLUDED_FROM_TRAINING} (canonical id 7)")
    print(f"{'local':>5} -> {'canonical':>9}  class")
    for local in sorted(MODEL_LOCAL_TO_CANONICAL):
        canonical = MODEL_LOCAL_TO_CANONICAL[local]
        note = "  <- canonical 8 (bread) maps to local 7" if local == 7 else ""
        print(f"{local:>5} -> {canonical:>9}  {MODEL_LOCAL_NAMES[local]}{note}")
    print(f"canonical -> local: {CANONICAL_TO_MODEL_LOCAL}")
    print()


def print_environment() -> None:
    print("Environment")
    print("-" * 11)
    print(f"python {platform.python_version()}  |  {platform.system()} {platform.release()}")
    try:
        import torch
        import ultralytics
        print(f"ultralytics {ultralytics.__version__}  |  torch {torch.__version__}  |  cuda {torch.cuda.is_available()}")
    except Exception as exc:
        print(f"WARNING: could not import ultralytics/torch: {exc}")
    print()


def scan_labels(dataset_root: Path):
    """Return (per-split image counts, model-local id histogram, bad ids found)."""
    counts, hist, bad = {}, defaultdict(int), set()
    for split in SPLITS:
        counts[split] = count_images(dataset_root / split / "images")
        labels_dir = dataset_root / split / "labels"
        if not labels_dir.is_dir():
            continue
        for label in labels_dir.glob("*.txt"):
            for raw in label.read_text(encoding="utf-8", errors="replace").splitlines():
                if not raw.strip():
                    continue
                try:
                    cid = int(float(raw.split()[0]))
                except (ValueError, IndexError):
                    bad.add("unparseable")
                    continue
                hist[cid] += 1
                if not (0 <= cid < NUM_TRAINING_CLASSES):
                    bad.add(cid)
    return counts, hist, bad


def check_leakage(dataset_root: Path) -> int:
    by_sha: dict[str, set] = defaultdict(set)
    for split in SPLITS:
        images_dir = dataset_root / split / "images"
        if not images_dir.is_dir():
            continue
        for image in images_dir.iterdir():
            if image.suffix.lower() in IMAGE_EXTENSIONS:
                by_sha[sha256_of(image)].add(split)
    return sum(1 for splits_in in by_sha.values() if len(splits_in) > 1)


def preflight(dataset_root: Path, yaml_path: Path, skip_leakage: bool) -> None:
    print("Preflight")
    print("-" * 9)

    if not yaml_path.is_file():
        raise SystemExit(f"FAIL: data yaml not found: {yaml_path}")
    if not dataset_root.is_dir():
        raise SystemExit(f"FAIL: dataset root not found: {dataset_root}. Run ml/build_balanced_training_dataset.py")

    for split in SPLITS:
        for leaf in ("images", "labels"):
            if not (dataset_root / split / leaf).is_dir():
                raise SystemExit(f"FAIL: missing {dataset_root / split / leaf}")

    counts, hist, bad = scan_labels(dataset_root)
    print(f"images: train={counts['train']} valid={counts['valid']} test={counts['test']}")
    if counts["train"] == 0 or counts["valid"] == 0:
        raise SystemExit("FAIL: train or valid split is empty.")

    print(f"model-local id histogram: {dict(sorted(hist.items()))}")
    if bad:
        raise SystemExit(f"FAIL: labels contain class ids outside 0..{NUM_TRAINING_CLASSES-1}: {sorted(bad)}")
    if 8 in hist:
        raise SystemExit("FAIL: canonical id 8 found in labels; bread must be model-local 7.")

    # Class distribution by name.
    print("class distribution (instances):")
    for local in range(NUM_TRAINING_CLASSES):
        print(f"  {local} {MODEL_LOCAL_NAMES[local]:16} {hist.get(local, 0)}")

    # Schema validation through ultralytics.
    try:
        from ultralytics.data.utils import check_det_dataset
        data = check_det_dataset(str(yaml_path))
    except Exception as exc:
        raise SystemExit(f"FAIL: data yaml did not load: {exc}")

    loaded = dict(data.get("names", {}))
    expected = training_names()
    if loaded != expected:
        raise SystemExit(f"FAIL: yaml names {loaded} != expected 8-class schema {expected}")
    if len(loaded) != NUM_TRAINING_CLASSES:
        raise SystemExit(f"FAIL: expected {NUM_TRAINING_CLASSES} classes, yaml has {len(loaded)}")
    for excluded in EXCLUDED_FROM_TRAINING:
        if excluded in loaded.values():
            raise SystemExit(f"FAIL: excluded class '{excluded}' present in the training yaml")
    if loaded.get(7) != "bread":
        raise SystemExit(f"FAIL: model-local id 7 must be 'bread', got {loaded.get(7)!r}")
    print("schema check: OK (8 classes, no counter, bread at local id 7)")

    if DEDUP_REPORT.is_file():
        print(f"dedup report present: {DEDUP_REPORT}")
    else:
        print(f"NOTE: no dedup report at {DEDUP_REPORT} (run ml/deduplicate_dataset.py)")

    if skip_leakage:
        print("leakage check: SKIPPED (--skip-leakage-check)")
    else:
        leaks = check_leakage(dataset_root)
        print(f"cross-split exact-duplicate groups: {leaks}")
        if leaks:
            raise SystemExit("FAIL: exact cross-split duplicate leakage remains. "
                             "Run ml/deduplicate_dataset.py --apply and rebuild.")

    print("Preflight PASSED.\n")


def smoke_check(yaml_path: Path) -> None:
    from ultralytics.data.utils import check_det_dataset
    print("Dataset-load smoke check (no training, no weight download)...")
    data = check_det_dataset(str(yaml_path))
    print(f"  names ({len(data['names'])}): {data['names']}")
    for split in ("train", "val", "test"):
        print(f"  {split}: {data.get(split)}")
    print("Dataset loads; schema matches the 8-class training schema.")


def train(yaml_path: Path, args) -> None:
    from ultralytics import YOLO
    print(f"Training: model={args.model} epochs={args.epochs} imgsz={args.imgsz} "
          f"batch={args.batch} device={args.device} workers={args.workers} seed={args.seed}")
    YOLO(args.model).train(
        data=str(yaml_path),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        seed=args.seed,
        project=args.project,
        name=args.name,
        exist_ok=True,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Hardened 8-class YOLO trainer / smoke-checker for TrackSense.")
    parser.add_argument("--model", default=None, help=f"REQUIRED for training. Recommended: {RECOMMENDED_MODEL}")
    parser.add_argument("--epochs", type=int, default=0, help="0 = no training.")
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--data", default=None, help="Explicit data yaml; default auto-generates from --dataset-root.")
    parser.add_argument("--dataset-root", default=str(DEFAULT_DATASET_ROOT))
    parser.add_argument("--name", default="tracksense_8class")
    parser.add_argument("--project", default=str(REPO_ROOT / "model" / "checkpoints" / "yolo_runs"))
    parser.add_argument("--smoke", action="store_true", help="Preflight + dataset-load check only.")
    parser.add_argument("--force-cpu-train", action="store_true", help="Allow real epochs on CPU (slow).")
    parser.add_argument("--skip-leakage-check", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    dataset_root = Path(args.dataset_root)

    print_environment()
    print_mapping()

    yaml_path = Path(args.data) if args.data else write_resolved_yaml(dataset_root)
    print(f"Data yaml: {yaml_path}")
    print(yaml_path.read_text(encoding="utf-8"))

    preflight(dataset_root, yaml_path, args.skip_leakage_check)

    if args.smoke:
        smoke_check(yaml_path)
        return

    if args.epochs > 0:
        if not args.model:
            raise SystemExit(f"--model is REQUIRED for training (no silent default). Recommended: {RECOMMENDED_MODEL}")
        try:
            import torch
            cuda = torch.cuda.is_available()
        except Exception:
            cuda = False
        if not cuda and args.device == "cpu" and not args.force_cpu_train:
            raise SystemExit(
                "No CUDA GPU and device=cpu: a multi-epoch run on CPU is impractical.\n"
                "Use --smoke locally and train on Colab T4, or pass --force-cpu-train to override."
            )
        train(yaml_path, args)
        return

    print("No action requested. Use --smoke, or --model <weights> --epochs N to train.")


if __name__ == "__main__":
    main()
