"""Evaluate the Random Forest risk classifier against its baselines (Step 8).

All models are compared on the SAME held-out test scenarios (grouped split by
scenario_id, seed 42 -- identical to training). Reports:

  reports/risk_model_metrics.json              all models + RF breakdowns
  reports/risk_model_classification_report.txt human-readable per-class report
  reports/risk_model_confusion_matrix.png      RF confusion matrix
  reports/risk_model_feature_importance.csv    RF importances (aggregated)

IMPORTANT: every number here is a SYNTHETIC-development result. The dataset is
generated by ml/generate_risk_training_data.py; these metrics say the model
learned the synthetic generating process's signal, NOT that it measures real
allergen transfer. This caveat is written into every output file.

Run: python evaluate/evaluate_random_forest.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
    roc_auc_score,
)

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ml.risk_baselines import get_baselines  # noqa: E402
from ml.risk_features import FEATURE_ORDER, RISK_CLASS_LABELS  # noqa: E402
from ml.train_random_forest import (  # noqa: E402
    LABEL_COLUMN,
    METADATA_PATH,
    MODEL_PATH,
    load_events,
    split_by_scenario,
    validate_dataframe,
)

REPORTS_DIR = "reports"
METRICS_PATH = os.path.join(REPORTS_DIR, "risk_model_metrics.json")
TEXT_REPORT_PATH = os.path.join(REPORTS_DIR, "risk_model_classification_report.txt")
CONFUSION_PATH = os.path.join(REPORTS_DIR, "risk_model_confusion_matrix.png")
IMPORTANCE_PATH = os.path.join(REPORTS_DIR, "risk_model_feature_importance.csv")

CLASS_IDS = list(range(len(RISK_CLASS_LABELS)))
SYNTHETIC_DISCLAIMER = (
    "SYNTHETIC-DEVELOPMENT RESULTS. Metrics reflect learning the synthetic "
    "generator's signal, not measured real-world allergen transfer."
)


class _ModelWrapper:
    """Uniform predict/predict_proba wrapper around the saved RF pipeline."""

    def __init__(self, pipeline):
        self.pipeline = pipeline
        self.classes_ = list(pipeline.named_steps["random_forest"].classes_)

    def predict(self, df):
        return self.pipeline.predict(df[FEATURE_ORDER]).astype(int)

    def predict_proba(self, df):
        proba = self.pipeline.predict_proba(df[FEATURE_ORDER])
        ordered = np.zeros((len(df), len(CLASS_IDS)))
        for col, class_id in enumerate(self.classes_):
            ordered[:, int(class_id)] = proba[:, col]
        return ordered


def _multiclass_brier(y_true, y_proba):
    onehot = np.zeros_like(y_proba)
    onehot[np.arange(len(y_true)), y_true] = 1.0
    return float(np.mean(np.sum((y_proba - onehot) ** 2, axis=1)))


def compute_metrics(y_true, y_pred, y_proba=None):
    precision, recall, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=CLASS_IDS, zero_division=0
    )
    metrics = {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "balanced_accuracy": float(balanced_accuracy_score(y_true, y_pred)),
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "weighted_f1": float(f1_score(y_true, y_pred, average="weighted", zero_division=0)),
        "per_class": {
            RISK_CLASS_LABELS[i]: {
                "precision": float(precision[i]),
                "recall": float(recall[i]),
                "f1": float(f1[i]),
                "support": int(support[i]),
            }
            for i in CLASS_IDS
        },
        "confusion_matrix": confusion_matrix(y_true, y_pred, labels=CLASS_IDS).tolist(),
        "roc_auc_ovr_macro": None,
        "brier_score": None,
    }
    if y_proba is not None:
        try:
            metrics["roc_auc_ovr_macro"] = float(
                roc_auc_score(y_true, y_proba, multi_class="ovr", average="macro", labels=CLASS_IDS)
            )
        except ValueError:
            metrics["roc_auc_ovr_macro"] = None  # e.g. a class missing from y_true
        metrics["brier_score"] = _multiclass_brier(np.asarray(y_true), np.asarray(y_proba))
    return metrics


def subgroup_metrics(y_true, y_pred, mask):
    if mask.sum() == 0:
        return None
    yt, yp = y_true[mask], y_pred[mask]
    return {
        "n": int(mask.sum()),
        "accuracy": float(accuracy_score(yt, yp)),
        "macro_f1": float(f1_score(yt, yp, average="macro", zero_division=0)),
    }


def rf_breakdowns(test_df, y_true, y_pred):
    """Performance sliced by exposure type, propagation depth, and cleaning."""
    is_allergen = test_df["is_source_allergen"].to_numpy().astype(int)
    depth = test_df["propagation_depth"].to_numpy().astype(int)
    cleaning = test_df["cleaning_detected"].to_numpy().astype(int)

    depth_bins = {"depth_0_direct": depth == 0, "depth_1_2": (depth >= 1) & (depth <= 2), "depth_3_plus": depth >= 3}
    return {
        "by_exposure": {
            "direct_source_contact": subgroup_metrics(y_true, y_pred, is_allergen == 1),
            "indirect_contact": subgroup_metrics(y_true, y_pred, is_allergen == 0),
        },
        "by_propagation_depth": {name: subgroup_metrics(y_true, y_pred, m) for name, m in depth_bins.items()},
        "by_cleaning_detected": {
            "cleaning_true": subgroup_metrics(y_true, y_pred, cleaning == 1),
            "cleaning_false": subgroup_metrics(y_true, y_pred, cleaning == 0),
        },
    }


def aggregated_feature_importance(pipeline) -> pd.DataFrame:
    """Sum one-hot object columns back to the original 15 schema features."""
    preprocess = pipeline.named_steps["preprocess"]
    rf = pipeline.named_steps["random_forest"]
    expanded_names = preprocess.get_feature_names_out()
    importances = rf.feature_importances_

    agg = {feature: 0.0 for feature in FEATURE_ORDER}
    for name, importance in zip(expanded_names, importances):
        body = name.split("__", 1)[1] if "__" in name else name
        if body.startswith("source_object"):
            agg["source_object"] += importance
        elif body.startswith("target_object"):
            agg["target_object"] += importance
        else:
            agg[body] += importance

    frame = pd.DataFrame(
        sorted(agg.items(), key=lambda kv: kv[1], reverse=True),
        columns=["feature", "importance"],
    )
    frame["importance"] = frame["importance"].round(6)
    return frame


def save_confusion_png(y_true, y_pred, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from sklearn.metrics import ConfusionMatrixDisplay

    cm = confusion_matrix(y_true, y_pred, labels=CLASS_IDS)
    display = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=RISK_CLASS_LABELS)
    fig, ax = plt.subplots(figsize=(5, 4.5))
    display.plot(ax=ax, cmap="Oranges", colorbar=False)
    ax.set_title("Random Forest risk model\n(SYNTHETIC development test set)")
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)


def _fmt_row(name, m):
    auc = "  n/a" if m["roc_auc_ovr_macro"] is None else f"{m['roc_auc_ovr_macro']:.3f}"
    brier = "  n/a" if m["brier_score"] is None else f"{m['brier_score']:.3f}"
    return (f"{name:<22} acc={m['accuracy']:.3f}  bal_acc={m['balanced_accuracy']:.3f}  "
            f"macroF1={m['macro_f1']:.3f}  wF1={m['weighted_f1']:.3f}  AUC={auc}  Brier={brier}")


def main():
    df = load_events()
    validate_dataframe(df)
    train_df, _val_df, test_df, _ids = split_by_scenario(df)

    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(f"No model at '{MODEL_PATH}'. Run ml/train_random_forest.py first.")
    rf = _ModelWrapper(joblib.load(MODEL_PATH))
    with open(METADATA_PATH, encoding="utf-8") as handle:
        metadata = json.load(handle)

    y_true = test_df[LABEL_COLUMN].to_numpy().astype(int)

    all_metrics = {}

    # Baselines (fit on the identical train split).
    for name, baseline in get_baselines().items():
        baseline.fit(train_df)
        y_pred = baseline.predict(test_df).astype(int)
        y_proba = baseline.predict_proba(test_df)
        all_metrics[name] = compute_metrics(y_true, y_pred, y_proba)

    # Random Forest.
    rf_pred = rf.predict(test_df)
    rf_proba = rf.predict_proba(test_df)
    rf_metrics = compute_metrics(y_true, rf_pred, rf_proba)
    rf_metrics["breakdowns"] = rf_breakdowns(test_df, y_true, rf_pred)
    all_metrics["Random Forest"] = rf_metrics

    # ---- console summary ----
    print(SYNTHETIC_DISCLAIMER)
    print(f"Test set: {len(test_df)} events / {test_df['scenario_id'].nunique()} scenarios\n")
    order = ["Majority class", "Direct-contact rule", "Logistic Regression", "Random Forest"]
    for name in order:
        print(_fmt_row(name, all_metrics[name]))
    print("\nRandom Forest per-class:")
    for label in RISK_CLASS_LABELS:
        pc = rf_metrics["per_class"][label]
        print(f"  {label:<6} precision={pc['precision']:.3f}  recall={pc['recall']:.3f}  "
              f"f1={pc['f1']:.3f}  support={pc['support']}")
    print("\nRandom Forest breakdowns (accuracy / macroF1):")
    for group, subs in rf_metrics["breakdowns"].items():
        print(f"  {group}:")
        for sub_name, sub in subs.items():
            if sub:
                print(f"    {sub_name:<22} n={sub['n']:<6} acc={sub['accuracy']:.3f}  macroF1={sub['macro_f1']:.3f}")

    # ---- artifacts ----
    os.makedirs(REPORTS_DIR, exist_ok=True)
    output = {
        "disclaimer": SYNTHETIC_DISCLAIMER,
        "model_version": metadata.get("model_version"),
        "dataset_path": metadata.get("dataset_path"),
        "test_rows": int(len(test_df)),
        "test_scenarios": int(test_df["scenario_id"].nunique()),
        "class_labels": RISK_CLASS_LABELS,
        "models": all_metrics,
    }
    with open(METRICS_PATH, "w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2)

    with open(TEXT_REPORT_PATH, "w", encoding="utf-8") as handle:
        handle.write(SYNTHETIC_DISCLAIMER + "\n\n")
        handle.write("Model comparison on held-out synthetic test scenarios\n")
        handle.write("=" * 70 + "\n")
        for name in order:
            handle.write(_fmt_row(name, all_metrics[name]) + "\n")
        handle.write("\nRandom Forest classification report (sklearn):\n")
        handle.write(classification_report(y_true, rf_pred, labels=CLASS_IDS,
                                           target_names=RISK_CLASS_LABELS, zero_division=0))
        handle.write("\nRandom Forest breakdowns (accuracy / macro-F1):\n")
        for group, subs in rf_metrics["breakdowns"].items():
            handle.write(f"  {group}:\n")
            for sub_name, sub in subs.items():
                if sub:
                    handle.write(f"    {sub_name:<22} n={sub['n']:<6} "
                                 f"acc={sub['accuracy']:.3f}  macroF1={sub['macro_f1']:.3f}\n")

    importance_df = aggregated_feature_importance(rf.pipeline)
    importance_df.to_csv(IMPORTANCE_PATH, index=False)

    save_confusion_png(y_true, rf_pred, CONFUSION_PATH)

    print(f"\nSaved: {METRICS_PATH}")
    print(f"Saved: {TEXT_REPORT_PATH}")
    print(f"Saved: {CONFUSION_PATH}")
    print(f"Saved: {IMPORTANCE_PATH}")
    print("\nTop features:")
    print(importance_df.head(6).to_string(index=False))


if __name__ == "__main__":
    main()
